language: python

python:
  - "3.5"

branches:
  only:
    - master

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

  - export ENV_NAME=travis

install:
  - conda create -c conda-forge --yes -n test python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - source activate test
  - pip install https://github.com/hgrecco/pint/archive/master.zip

script:
  # pyEQL
  - git clone --depth 1 --branch 0.3.1 https://github.com/rkingsbury/pyEQL
  - cd pyEQL
  - python -m unittest pyEQL/tests/*

